# Generated by Django 3.0.8 on 2020-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20200920_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='birthday',
            field=models.BigIntegerField(default=1600858272, null=True, verbose_name='出生日期'),
        ),
    ]
