# Generated by Django 3.0.8 on 2020-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0002_auto_20200920_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='index',
            field=models.SmallIntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期天')], default=1, unique=True, verbose_name='位置'),
        ),
    ]
