# Generated by Django 3.0.8 on 2020-09-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='Date',
            new_name='date',
        ),
    ]
