# Generated by Django 3.0.8 on 2020-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular', '0002_auto_20200920_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular',
            name='creation_time',
            field=models.BigIntegerField(blank=True, default=1600858272, verbose_name='创建时间'),
        ),
    ]
